/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apksederhana;

/**
 *
 * @author HP 14s
 */
public class PERSEGI extends javax.swing.JFrame {

    /**
     * Creates new form PERSEGI
     */
    public PERSEGI() {
        initComponents();
        reset();
    }
    void reset(){
        tNilaiA.setText(null);
        tNilaiB.setText(null);
        fLuas.setText(null);
        fKeliling.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPersegi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tNilaiA = new javax.swing.JTextField();
        tHitung = new javax.swing.JButton();
        tReset = new javax.swing.JButton();
        tKembali = new javax.swing.JButton();
        fLuas = new javax.swing.JLabel();
        fKeliling = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNilaiB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPersegi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPersegi.setText("PERSEGI");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MASUKKAN ANGKA A");

        tHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apksederhana/plus.png"))); // NOI18N
        tHitung.setText("HITUNG");
        tHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHitungActionPerformed(evt);
            }
        });

        tReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apksederhana/reset.png"))); // NOI18N
        tReset.setText("RESET");
        tReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tResetActionPerformed(evt);
            }
        });

        tKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apksederhana/arrow.png"))); // NOI18N
        tKembali.setText("KEMBALI");
        tKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKembaliActionPerformed(evt);
            }
        });

        fLuas.setText("jLabel2");

        fKeliling.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("MASUKKAN ANGKA B");

        tNilaiB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNilaiBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jPersegi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tHitung)
                                .addGap(45, 45, 45)
                                .addComponent(tReset)
                                .addGap(51, 51, 51)
                                .addComponent(tKembali))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(57, 57, 57)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tNilaiA, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                            .addComponent(tNilaiB))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPersegi)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNilaiB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tHitung)
                    .addComponent(tReset)
                    .addComponent(tKembali))
                .addGap(35, 35, 35)
                .addComponent(fLuas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fKeliling)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_tResetActionPerformed

    private void tKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKembaliActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_tKembaliActionPerformed

    private void tHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHitungActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(tNilaiA.getText());
        int b = Integer.parseInt(tNilaiB.getText());
        int Luas = a * b;
        int Keliling = a * 4;
        fLuas.setText("Luas : "+Luas); 
        fKeliling.setText("Keliling : "+Keliling);
    }//GEN-LAST:event_tHitungActionPerformed

    private void tNilaiBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNilaiBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNilaiBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PERSEGI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fKeliling;
    private javax.swing.JLabel fLuas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jPersegi;
    private javax.swing.JButton tHitung;
    private javax.swing.JButton tKembali;
    private javax.swing.JTextField tNilaiA;
    private javax.swing.JTextField tNilaiB;
    private javax.swing.JButton tReset;
    // End of variables declaration//GEN-END:variables
}
